baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'blogLuis'
theme = 'congo'

[menu]
  [[menu.main]]
    name = "Inicio"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Markdown"
    url = "/explicacion_markdown/"
    weight = 2

  [[menu.main]]
    name = "Galería de Imágenes"
    url = "/galeria_imagenes/"
    weight = 3

  [[menu.main]]
    name = "Canales de TV"
    url = "/canales_tv/"
    weight = 4

  [[menu.main]]
    name = "Contenido de Programación"
    url = "/conteido_programacion/"
    weight = 5